name: Test with Gradle

on:
  [workflow_dispatch]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Test with Gradle
      run: ./gradlew test
    - name: Test Report
      uses: phoenix-actions/test-reporting@41efe7ebebe7ef156ef46f6b0acf50ec0f10315b # https://github.com/phoenix-actions/test-reporting/releases/tag/v12
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Tests            # Name of the check run which will be created
        path: app/build/test-results/**/*.xml    # Path to test results
        reporter: java-junit
        output-to: step-summary
